name: Build

on:

  push:
    branches: [ main ]
    paths-ignore:
    - 'doc/**'
    - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Test
      run: dotnet test --configuration Release --logger GitHubActions

    - name: Pack with dotnet
      run: dotnet pack Jint/Jint.csproj --output artifacts --configuration Release -p:VersionSuffix=preview-$GITHUB_RUN_NUMBER -p:ContinuousIntegrationBuild=True
